name: 'default'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  readiness:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: 'setup node'
        with:
          node-version: '14.x'

      - name: 'Install npm dependencies'
        run: yarn install

      - name: 'Test CLI'
        run: yarn test