name: 'default'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  readiness:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: 'Setup node'
        with:
          node-version: '16.x'

      - name: 'Install npm dependencies'
        run: yarn install

      - name: 'Refresh monoreact root dependency'
        run: yarn add ./cli -D -W

      - name: 'Test CLI'
        run: yarn test --ci